title: Mod Translator
logo: images\mtfm_logo.ico
repository_link: https://github.com/steklyashka33/Minecraft-Mod-Translator

system_list_of_appearance_modes:
- System
- Light
- Dark

folder_with_translations: lang
folder_with_images: images