title: Mod Translator

system_list_of_appearance_modes:
- System
- Light
- Dark

folder_with_translations: "/lang"
folder_with_images: "/images"

user_config_template:
  interface_language: English #language name
  dict_interface_language: null #example:  English: en.yaml
  appearance_mode: 0  #number from the list system_list_of_appearance_modes
  last_path_entry: ''